### PR TITLE
Version 1.2.2

### PR DESCRIPTION
**Pull request by MillerMedia**

### CODE REVIEW

**Comment by bizmate** [comment]
thank you for merging my PR, I hope this can be merged soon so we can add it to our project

**Comment by MillerMedia** [comment]
@bizmate We should have this new version up today.

Do you have a Wordpress.org username btw? I can add you to the list of contributors to the plugin on the WordPress repo if so. Thanks!

**Comment by MillerMedia** [comment]
@bizmate Also, if you do have a Wordpress.org username, it would be great to get a five star review on the plugin:

https://wordpress.org/plugins/send-emails-with-mandrill/

This way we can get more visibility, which should result in more developers getting involved in improving the plugin. Thanks!

**Comment by MillerMedia** [comment]
@bizmate FYI, new version is live!

**Pull request merged**
