### PR TITLE
Removed RSS feed due to longstanding unfixed warnings in SimplePie:

### PR DESCRIPTION
**Pull request by MillerMedia**
https://github.com/Miller-Media/send-emails-with-mandrill/issues/11

### CODE REVIEW

**Comment by MillerMedia** [comment]
There is an issue in SimplePie that is throwing the error:

Warning: A non-numeric value encountered in /Users/mattmiller/Sites/wordpress/wp-includes/SimplePie/Parse/Date.php on line 694

As the plugin iterates through the Mandrill / MailChimp RSS feed items on the right sidebar in the settings screen. The only way to fix the issue and maintain the feed correctly is to edit the code in the SimplePie library bundled in with the WordPress core.

Since we don't want to edit core and there are outstanding issues in the WordPress trac and SimplePie repositories, I propose we swap out the use of SimplePie to read the RSS feeds for a more modern library. Help wanted. Thanks!

**Comment by bizmate** [comment]
i just realised you have this PR open, my PR is similar but it still shows the Feed if and when the SimplePie bugs get fixed. Either way it would be great to merge it 

cheers https://github.com/Miller-Media/send-emails-with-mandrill/pull/34

**Comment by MillerMedia** [comment]
Closing this in favor of PR #34

**Comment by bizmate** [comment]
As per the message on https://github.com/Miller-Media/send-emails-with-mandrill/pull/34
the translations at https://github.com/Miller-Media/send-emails-with-mandrill/blob/741b545505b127612e5f34c4e0c9e0fcad17ffe0/lang/wpmandrill.po#L258-L264
and
https://github.com/Miller-Media/send-emails-with-mandrill/blob/741b545505b127612e5f34c4e0c9e0fcad17ffe0/lang/wpmandrill-es_ES.po#L262-L268
should be removed and MO files regenerated if this PR is re-opened.

**Comment by MillerMedia** [comment]
@bizmate Nice catch. Let's have you update that in your PR ( #34 ) and we will merge that change in. Thanks!

**Pull request closed without merging**
