### PR TITLE
Fixes for #15 #21 and partial fix for #23 - and additional fix for #36

### PR DESCRIPTION
**Pull request by andrewhilson**
Fixed issue #21 , #15 and removes the 500 error in #23 due to unsupported API call (URL tracking removed).

### CODE REVIEW

**Comment by andrewhilson** [comment]
Added fix for issue #36

**Comment by MillerMedia** [comment]
This is great, thanks @andrewhilson ! We'll get some QA done on this later today and either come back with notes or merge it in. This is a huge help!

**Comment by andrewhilson** [comment]
No problem @MillerMedia... I used the old plugin with a lot of WP sites and happy to contribute to this fork.

**Comment by MillerMedia** [comment]
Hi @andrewhilson one thing we're having a bit of trouble with is that the different commits are all wrapped into this same PR. Could you break each of the issue fixes/features into their own PRs.

I want to make sure that we are able to QA each of the new updates individually. I'm going to update the policy on our README for that. For example, the 'return true' statement is a bit more urgent than subaccounts and want the ability to phase some of these updates out. Thanks!

**Comment by andrewhilson** [comment]
@MillerMedia will close this PR and create separate PRs now.

**Pull request closed without merging**
