### PR TITLE
Fixes 500 error issue #23

### PR DESCRIPTION
**Pull request by andrewhilson**
Fixes 500 error in #23

### CODE REVIEW

**Comment by MillerMedia** [comment]
@andrewhilson Should we remove the urls_list() function as well now that we are not using it?

Also, can we put try/catch blocks (or some sort of error handling) on the other API calls to prevent this from breaking if support for other endpoints go away as well?

**Comment by andrewhilson** [comment]
@MillerMedia I was going to remove it, but it's still published on the Mandrill API docs (!) https://mandrillapp.com/api/docs/urls.JSON.html

I'm not sure the best approach here... Mailchimp have somewhat distanced Mandrill as a product and theres a general lack of communication for developers. 

I believe there already is error handling for all of the other API calls; but that dashboard widget and reporting page is just a horror show. I would be inclined to remove it entirely because of it's huge load time and general uselessness!

**Comment by MillerMedia** [comment]
Ok, for this PR let's just remove that function and then we can take a bigger approach for the stats screen altogether. I haven't familiarized myself with the extent of what Mandrill's API returns these days but as an integration between WordPress and Mandrill, I think support for as much data back and forth that we can support would be great.

Ultimately, it would be great for users to be able to manage as many Mandrill settings, data and stats from the WordPress dashboard as possible, given that it's efficient.

**Comment by andrewhilson** [comment]
Sure - do you want me to remove that function from mandrill.class.php and push it to the branch?

**Comment by andrewhilson** [comment]
@MillerMedia just committed.

**Comment by MillerMedia** [comment]
Looks great! Will merge in for the next release. Thanks!

**Pull request merged**
